#!/usr/bin/env python

import argparse
parser = argparse.ArgumentParser()

parser.add_argument("-p","--path", required=True, help="path to the sensor")
parser.add_argument("-v", "--verbose", action="store_true", help="increase output verbosity")

args = parser.parse_args()

# generate a dummy sensor value. in general, this would come from polling a sensor via args.path

sensorValue=18.6

if args.verbose:
    print "sensor value via path {}: {}".format(args.path, sensorValue)
else:
    print sensorValue
